# Generated by Django 4.0.5 on 2022-06-10 20:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=64)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.cd')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.rental')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=64)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.rental')),
            ],
        ),
        migrations.AddField(
            model_name='cd',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.rental'),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=64)),
                ('isbn', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(13)])),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.rental')),
            ],
        ),
    ]
